name: 'Checkout and run yarn'
description: 'This action checks out the commit, sets up Node and installs deps using yarn.'
author: 'eventespresso'
inputs:
    name: pratheesh
      description: enter user data
      default: "pratheeshb"

runs:
  using: 'composite'
  steps:
  - name: From composite action
    run: |
    echo "Hello ${{ inputs.name }}"
     
